// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseRedisConnection() {
  return window['go']['main']['App']['CloseRedisConnection']();
}

export function ConnectToRedis(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectToRedis'](arg1, arg2, arg3);
}

export function ExecuteRedisCommand(arg1) {
  return window['go']['main']['App']['ExecuteRedisCommand'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
